development:
  strategy: oauth
  oauth_consumer_key: 1uZafnd3rD8mwrgeVVybg
  oauth_consumer_secret: 4DLRGQ4R33Rj6EmE3hAyKZjsq6YU7g3xbLi9I9XMI
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: 1uZafnd3rD8mwrgeVVybg
  oauth_consumer_secret: 4DLRGQ4R33Rj6EmE3hAyKZjsq6YU7g3xbLi9I9XMI
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: FbNiMUNky9ZiP4GlVTc5Fg
  oauth_consumer_secret: hnryEf8lljOv44kWygepTYv4b7MQOcEEfxt9rN0 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
staging:
  strategy: oauth
  oauth_consumer_key: 1uZafnd3rD8mwrgeVVybg
  oauth_consumer_secret: 4DLRGQ4R33Rj6EmE3hAyKZjsq6YU7g3xbLi9I9XMI 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
